module.exports = [
  { title: "food delivery", icon: "mdi-moped" },
  { title: "movie streaming", icon: "mdi-movie" },
  { title: "music streaming", icon: "mdi-headphones" },
  { title: "food groceries", icon: "mdi-cart-variant" },
  { title: "drug groceries", icon: "mdi-lipstick" },
  { title: "books", icon: "mdi-book" },
  { title: "food delivery", icon: "mdi-basket-outline" },
  { title: "coffee", icon: "mdi-coffee-to-go" },
  { title: "online shop", icon: "mdi-basket" },
  { title: "other", icon: "mdi-cash" },
  { title: "backery", icon: "mdi-cupcake" },
  { title: "games", icon: "mdi-gamepad-variant-outline" },
  { title: "clothes", icon: "mdi-hanger" },
  { title: "electronics", icon: "mdi-remote-tv" },
  { title: "rent", icon: "mdi-home-city" },
  { title: "phone", icon: "mdi-phone" },
  { title: "internet", icon: "mdi-at" },
  { title: "subscription", icon: "mdi-playlist-check" },
  { title: "restaurant", icon: "mdi-silverware-fork-knife" },
  { title: "fincance", icon: "mdi-bank" },
];
