GET http://localhost:3000

### 404 Route
GET http://localhost:3000/bullshit


# AUTH ROUTES
### Register
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "other@app.com",
    "password": "12345678",
    "name":"Stephan"
}

### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "admin@app.com",
    "password": "admin1234"
}

### Logout
DELETE http://localhost:3000/auth/logout
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWRtaW4iLCJpYXQiOjE2MTA5ODc2MDcsImV4cCI6MTY0MjU0NTIwNywiYXVkIjoiNWZkOGM5MmUxZDQyNjIyNDJkZDY0MWMzIiwiaXNzIjoiYnVkZ2V0cy5pbyJ9.VhmsLY9PKGIkMPdWKyK6XOSxLbqaF_0c-o4x2A6lsOg"
}


### Refresh Token
POST http://localhost:3000/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiU3RlcGhhbiIsImlhdCI6MTYwNzk2MjU2MiwiZXhwIjoxNjM5NTIwMTYyLCJhdWQiOiI1ZmQ3OGY5MDBmZjg4NjA1N2Y2Mzg3MmMiLCJpc3MiOiJidWRnZXRzLmlvIn0.FZKPCnWD6TvZLl78hDwi6bC9T9yfMkkOuwoYXxaAk68"
}



