### GET ALL SELLING POINTS FROM USER
GET http://localhost:3000/sellingpoints
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWRtaW4iLCJyb2xlIjoiYWRtaW4iLCJtYWluVmF1bHQiOiI1ZmQ5MGMzMGYxNGY3NzA3OGQ1YzgyNGUiLCJpYXQiOjE2MDg0NzIzMDEsImV4cCI6MTYwODQ3OTUwMSwiYXVkIjoiNWZkOGM5MmUxZDQyNjIyNDJkZDY0MWMzIiwiaXNzIjoiYnVkZ2V0cy5pbyJ9.QG3eCPzC_aMuJ8Ns-R-5dZjYl4jwdmGJnqAITd7xDEU


### GET ALL CREATE SELLING POINTS FROM VAULT
GET http://localhost:3000/sellingpoints/5fdf571336b31807d75f029a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiU3RlcGhhbiIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjA4NDcyNTk2LCJleHAiOjE2MDg0Nzk3OTYsImF1ZCI6IjVmZGY1Mzg3ZmU3ZGQ2MDVhYjQ5NGUxNCIsImlzcyI6ImJ1ZGdldHMuaW8ifQ.guj48sXiu5Z1rePxOa4gMRWJQmRkKaclpknUEyYXbHs

### CREATE SELLING POINT
POST http://localhost:3000/sellingpoints
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWRtaW4iLCJyb2xlIjoiYWRtaW4iLCJtYWluVmF1bHQiOiI1ZmQ5MGMzMGYxNGY3NzA3OGQ1YzgyNGUiLCJpYXQiOjE2MDg0NzIzMDEsImV4cCI6MTYwODQ3OTUwMSwiYXVkIjoiNWZkOGM5MmUxZDQyNjIyNDJkZDY0MWMzIiwiaXNzIjoiYnVkZ2V0cy5pbyJ9.QG3eCPzC_aMuJ8Ns-R-5dZjYl4jwdmGJnqAITd7xDEU
Content-Type: application/json

{
    "name":"Alnatura",
    "initials": "AN",
    "category": "foodGroceries"
}


### EDIT CREATE SELLING POINT
PUT http://localhost:3000/sellingpoints/5fdf571336b31807d75f029a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWRtaW4iLCJyb2xlIjoiYWRtaW4iLCJtYWluVmF1bHQiOiI1ZmQ5MGMzMGYxNGY3NzA3OGQ1YzgyNGUiLCJpYXQiOjE2MDg0NzI3NzIsImV4cCI6MTYwODQ3OTk3MiwiYXVkIjoiNWZkOGM5MmUxZDQyNjIyNDJkZDY0MWMzIiwiaXNzIjoiYnVkZ2V0cy5pbyJ9.zs6aShSbpYupSfEhow2oeCcMKHgZYZ5OidTqIp3jOYk
Content-Type: application/json

{
    "name":"Tester Hans",
    "initials": "TH",
    "category": "foodGroceries"
}


### DELETE CREATE SELLING POINT
DELETE http://localhost:3000/sellingpoints/5fdf52e5c29403054ae1af6e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWRtaW4iLCJyb2xlIjoiYWRtaW4iLCJtYWluVmF1bHQiOiI1ZmQ5MGMzMGYxNGY3NzA3OGQ1YzgyNGUiLCJpYXQiOjE2MDg0NzIzMDEsImV4cCI6MTYwODQ3OTUwMSwiYXVkIjoiNWZkOGM5MmUxZDQyNjIyNDJkZDY0MWMzIiwiaXNzIjoiYnVkZ2V0cy5pbyJ9.QG3eCPzC_aMuJ8Ns-R-5dZjYl4jwdmGJnqAITd7xDEU
