### AS ADMIN GET ALL USERS
GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWRtaW4iLCJyb2xlIjoiYWRtaW4iLCJtYWluVmF1bHQiOiI1ZmQ4Y2ZiMDcwNDc4ZjI2Y2QwMjQ3NGEiLCJpYXQiOjE2MDgwNjA0MzIsImV4cCI6MTYwODA2NzYzMiwiYXVkIjoiNWZkOGM5MmUxZDQyNjIyNDJkZDY0MWMzIiwiaXNzIjoiYnVkZ2V0cy5pbyJ9.-lqln7VAmWxXUSQljCqkRI7_q8_qdsTSoLgVkY1DAco


### EDIT A USER
PUT http://localhost:3000/users/5fd90e4b93b2a808f78a96c0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWRtaW4iLCJyb2xlIjoiYWRtaW4iLCJtYWluVmF1bHQiOiI1ZmQ4Y2ZiMDcwNDc4ZjI2Y2QwMjQ3NGEiLCJpYXQiOjE2MDgwNjA0MzIsImV4cCI6MTYwODA2NzYzMiwiYXVkIjoiNWZkOGM5MmUxZDQyNjIyNDJkZDY0MWMzIiwiaXNzIjoiYnVkZ2V0cy5pbyJ9.-lqln7VAmWxXUSQljCqkRI7_q8_qdsTSoLgVkY1DAco
Content-Type: application/json

{
    "email": "edit@app.com",
    "password": "12345678",
    "name":"Stephan edit"
}


### DELETE A USER
DELETE http://localhost:3000/users/5fd90e4b93b2a808f78a96c0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWRtaW4iLCJyb2xlIjoiYWRtaW4iLCJtYWluVmF1bHQiOiI1ZmQ4Y2ZiMDcwNDc4ZjI2Y2QwMjQ3NGEiLCJpYXQiOjE2MDgwNjA0MzIsImV4cCI6MTYwODA2NzYzMiwiYXVkIjoiNWZkOGM5MmUxZDQyNjIyNDJkZDY0MWMzIiwiaXNzIjoiYnVkZ2V0cy5pbyJ9.-lqln7VAmWxXUSQljCqkRI7_q8_qdsTSoLgVkY1DAco

### SET MAIN VAULT FOR USER
POST http://localhost:3000/users/5fd8c92e1d4262242dd641c3/mainvault/5fd90c30f14f77078d5c824e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWRtaW4iLCJyb2xlIjoiYWRtaW4iLCJtYWluVmF1bHQiOiI1ZmQ4Y2ZiMDcwNDc4ZjI2Y2QwMjQ3NGEiLCJpYXQiOjE2MDgwNjA0MzIsImV4cCI6MTYwODA2NzYzMiwiYXVkIjoiNWZkOGM5MmUxZDQyNjIyNDJkZDY0MWMzIiwiaXNzIjoiYnVkZ2V0cy5pbyJ9.-lqln7VAmWxXUSQljCqkRI7_q8_qdsTSoLgVkY1DAco