
# VAULTS
### GET ALL VAULTS
GET http://localhost:3000/vaults
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWRtaW4iLCJpYXQiOjE2MDgwMzk5MDIsImV4cCI6MTYwODA0NzEwMiwiYXVkIjoiNWZkNzk0YTI3OWExNDYwN2FjNTdlY2FlIiwiaXNzIjoiYnVkZ2V0cy5pbyJ9.waXVWZ_v6Z-JQgWz03UQdlF5Gr372wemrkoxOxTHo_0


### CREATE A VAULT
POST http://localhost:3000/vaults
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiU3RlcGhhbiIsImlhdCI6MTYwODAzOTMxMywiZXhwIjoxNjA4MDQ2NTEzLCJhdWQiOiI1ZmQ4YmIzMGM2YmMyMzFkNTI3YTNmNzMiLCJpc3MiOiJidWRnZXRzLmlvIn0.zjuGPs3b2TdCG84Ec5R0ngEUocXFBBMOLAmXL8N8TZg
Content-Type: application/json

{
    "name":"Stephans Vault"
}

### EDIT A VAULT
PUT http://localhost:3000/vaults/5fd7b273efcac91284245879
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWRtaW4iLCJpYXQiOjE2MDc5NzQ5MjEsImV4cCI6MTYwNzk4MjEyMSwiYXVkIjoiNWZkNzk0YTI3OWExNDYwN2FjNTdlY2FlIiwiaXNzIjoiYnVkZ2V0cy5pbyJ9.-YsSipz4-ZUgpN0rkXGU1QhHqqyKxYgeaOM3NcQL8r4
Content-Type: application/json

{
    "name":"edit vault 2"
}

### DELETE A VAULT
DELETE http://localhost:3000/vaults/5fd7b273efcac91284245879
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWRtaW4iLCJpYXQiOjE2MDc5NzQ5MjEsImV4cCI6MTYwNzk4MjEyMSwiYXVkIjoiNWZkNzk0YTI3OWExNDYwN2FjNTdlY2FlIiwiaXNzIjoiYnVkZ2V0cy5pbyJ9.-YsSipz4-ZUgpN0rkXGU1QhHqqyKxYgeaOM3NcQL8r4





# VAULT SHARING
### Share a vault
POST http://localhost:3000/vaults/5fd8bc5e50e62f1deb0d75a0/share/5fd794a279a14607ac57ecae
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiU3RlcGhhbiIsImlhdCI6MTYwODAzOTMxMywiZXhwIjoxNjA4MDQ2NTEzLCJhdWQiOiI1ZmQ4YmIzMGM2YmMyMzFkNTI3YTNmNzMiLCJpc3MiOiJidWRnZXRzLmlvIn0.zjuGPs3b2TdCG84Ec5R0ngEUocXFBBMOLAmXL8N8TZg
### Share a vault
DELETE http://localhost:3000/vaults/5fd8bc5e50e62f1deb0d75a0/share/5fd794a279a14607ac57ecae
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiU3RlcGhhbiIsImlhdCI6MTYwODAzOTkyMywiZXhwIjoxNjA4MDQ3MTIzLCJhdWQiOiI1ZmQ4YmIzMGM2YmMyMzFkNTI3YTNmNzMiLCJpc3MiOiJidWRnZXRzLmlvIn0.MWClIq5i0sDxwCBZ4lfQnveu4Ve-Ij6YKA6m85DA1JI
