
# VAULTS
### GET ALL VAULTS
GET http://localhost:3000/vaults
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWRtaW4iLCJyb2xlIjoiYWRtaW4iLCJtYWluVmF1bHQiOiI1ZmQ4ZDFjMzE5MDdhNjI3YmZkNmY2NzQiLCJpYXQiOjE2MDgwNDU1NTQsImV4cCI6MTYwODA1Mjc1NCwiYXVkIjoiNWZkOGM5MmUxZDQyNjIyNDJkZDY0MWMzIiwiaXNzIjoiYnVkZ2V0cy5pbyJ9.kx32uNZkwsT5acQ_qnWrA1kOqsammj5OkljSiLC9fs0

### CREATE A VAULT
POST http://localhost:3000/vaults
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiU3RlcGhhbiIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjA4MDQ0OTYzLCJleHAiOjE2MDgwNTIxNjMsImF1ZCI6IjVmZDhkMWEzMTkwN2E2MjdiZmQ2ZjY3MyIsImlzcyI6ImJ1ZGdldHMuaW8ifQ.2EsITgmvZRjmmc7BIZ7ZeIrPOwM4XxRYkS1PJLID4_k
Content-Type: application/json

{
    "name":"Stephans VAULT"
}

### EDIT A VAULT
PUT http://localhost:3000/vaults/5fd7b273efcac91284245879
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWRtaW4iLCJpYXQiOjE2MDc5NzQ5MjEsImV4cCI6MTYwNzk4MjEyMSwiYXVkIjoiNWZkNzk0YTI3OWExNDYwN2FjNTdlY2FlIiwiaXNzIjoiYnVkZ2V0cy5pbyJ9.-YsSipz4-ZUgpN0rkXGU1QhHqqyKxYgeaOM3NcQL8r4
Content-Type: application/json

{
    "name":"edit vault 2"
}

### DELETE A VAULT
DELETE http://localhost:3000/vaults/5fd7b273efcac91284245879
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWRtaW4iLCJpYXQiOjE2MDc5NzQ5MjEsImV4cCI6MTYwNzk4MjEyMSwiYXVkIjoiNWZkNzk0YTI3OWExNDYwN2FjNTdlY2FlIiwiaXNzIjoiYnVkZ2V0cy5pbyJ9.-YsSipz4-ZUgpN0rkXGU1QhHqqyKxYgeaOM3NcQL8r4





# VAULT SHARING
### Share a vault
POST http://localhost:3000/vaults/5fd8d1c31907a627bfd6f674/share/5fd8c92e1d4262242dd641c3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiU3RlcGhhbiIsInJvbGUiOiJ1c2VyIiwibWFpblZhdWx0IjoiNWZkOGQxYzMxOTA3YTYyN2JmZDZmNjc0IiwiaWF0IjoxNjA4MDQ1NDk1LCJleHAiOjE2MDgwNTI2OTUsImF1ZCI6IjVmZDhkMWEzMTkwN2E2MjdiZmQ2ZjY3MyIsImlzcyI6ImJ1ZGdldHMuaW8ifQ.a3t1vK08BMRjo4NP_4oyW4aKBa0BGdwBjy9BHfl1Abk
### Share a vault
DELETE http://localhost:3000/vaults/5fd8d1c31907a627bfd6f674/share/5fd8c92e1d4262242dd641c3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiU3RlcGhhbiIsInJvbGUiOiJ1c2VyIiwibWFpblZhdWx0IjoiNWZkOGQxYzMxOTA3YTYyN2JmZDZmNjc0IiwiaWF0IjoxNjA4MDQ1NzE0LCJleHAiOjE2MDgwNTI5MTQsImF1ZCI6IjVmZDhkMWEzMTkwN2E2MjdiZmQ2ZjY3MyIsImlzcyI6ImJ1ZGdldHMuaW8ifQ.HPP8NBUUK9mYas89Y9XqVyRHNc7r4jjqg44ZHlXmJQU
