GET http://localhost:3000

### 404 Route
GET http://localhost:3000/bullshit


# AUTH ROUTES
### Register
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "admin@app.com",
    "password": "12345678",
    "name":"Stephan"
}

### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "admin@app.com",
    "password": "12345678"
}

### Logout
DELETE http://localhost:3000/auth/logout
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiU3RlcGhhbiIsImlhdCI6MTYwNzk2MjU3MCwiZXhwIjoxNjM5NTIwMTcwLCJhdWQiOiI1ZmQ3OGY5MDBmZjg4NjA1N2Y2Mzg3MmMiLCJpc3MiOiJidWRnZXRzLmlvIn0.olZlHukVvRwZqmj4Z3jlm4-sx26Khju4T16umC7iBzc"
}


### Refresh Token
POST http://localhost:3000/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiU3RlcGhhbiIsImlhdCI6MTYwNzk2MjU2MiwiZXhwIjoxNjM5NTIwMTYyLCJhdWQiOiI1ZmQ3OGY5MDBmZjg4NjA1N2Y2Mzg3MmMiLCJpc3MiOiJidWRnZXRzLmlvIn0.FZKPCnWD6TvZLl78hDwi6bC9T9yfMkkOuwoYXxaAk68"
}