GET http://localhost:3000

### 404 Route
GET http://localhost:3000/bullshit


# AUTH ROUTES
### Register
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "admin@app.com",
    "password": "12345678",
    "name":"Stephan"
}

### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "admin@app.com",
    "password": "12345678"
}

### Logout
DELETE http://localhost:3000/auth/logout
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiU3RlcGhhbiIsImlhdCI6MTYwNzUyNjEyMCwiZXhwIjoxNjM5MDgzNzIwLCJhdWQiOiI1ZmQwZTU4ZmMwOGE5YzA0YWYxZDE0OWQiLCJpc3MiOiJidWRnZXRzLmlvIn0.QKAQB_hwpkrhlkcjoQDpBba85TInNNc0xyZw6rqtRwQ"
}


### Refresh Token
POST http://localhost:3000/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiU3RlcGhhbiIsImlhdCI6MTYwNzUyNjExMSwiZXhwIjoxNjM5MDgzNzExLCJhdWQiOiI1ZmQwZTU4ZmMwOGE5YzA0YWYxZDE0OWQiLCJpc3MiOiJidWRnZXRzLmlvIn0.BiLsY68APzbsJxFan7e6xdaLRpakrCMM-JvpacbSMhk"
}